### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tejmagar** [JoMingyu/google-play-scraper#139]
**google_play_scraper.1.2.0**

The top featured app does not appear in the result

appId: tej.wifithiefdetector is featured in Position 1 in the Philippines but it is excluded in the result
For example, https://play.google.com/store/search?q=WiFi%20thief%20detector&c=apps&hl=en&gl=PH
```
search(
            query='WiFi Thief Detector',
            lang="en",
            country='PH',
            n_hits=30
        )
```

**Expected behavior**
1st position featured app is also expected to appear on the results

**Comment by JoMingyu** [comment]
It works well on my machine and library version 1.2.2. If the same problem occurs after updating the library, please reopen issue.

**Comment by Arsh1219** [comment]
same issue. if we search for "facebook lite" or "Instagram lite", the result doesn't show the match.

**Comment by Canonize** [comment]
Same problem here. Missing the most similar match when using the exact query, for example, search("pokemongo") won't return "Pokémon GO", but search("best Pikachu game") will. Guess it's due to the search page difference?
![image](https://github.com/JoMingyu/google-play-scraper/assets/53464670/9b8409b3-092b-477f-b582-63d415876cf5)
