### ISSUE TITLE
Number review different from total number

### ISSUE THREAD

**Issue by darannu86** [JoMingyu/google-play-scraper#54]
I am testing google-play-scraper and I tried to test it on:
https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni&hl=it

but I dont understand why I get only 9000 reviews while we have almost 20000 downloads.

Also I would like to know the parameters I can use for Sort.

**Comment by JoMingyu** [comment]
### why I get only 9000 reviews while we have almost 20000 downloads.
related to #50 

You can leave only a star rating in the Google Play review without any content. Since reviews without these details are not displayed on the review page of Google Play, the `reviews` function returns the result excluding reviews with only a star rating.

I will write these context to readme.md as troubleshooting.

### I would like to know the parameters I can use for Sort.
You can use `Sort.NEWEST`, `Sort.RATING`, `Sort.MOST_RELEVANT` to `sort` argument of `reviews` function.
